variable "aws_access_key"              {}
variable "aws_secret_key"              {}
variable "aws_region"                  {}
variable "aws_profile"                 {}
variable "dev_bucket_id"               {}
variable "default_lambda_role_arn"     {}
variable "lambda_layer_arn"            {}
variable "api_gateway_arn"             {}
variable "api_gateway_id"              {}
variable "root_resource_id"            {}
variable "service_domain"              {}
variable "service_bucket_arn"          {}
variable "service_bucket_id"           {}