variable "aws_region"                  {}
variable "aws_profile"                 {}
variable "storage_bucket_id"           {}
variable "dev_bucket_id"               {}
variable "public_subnet_id"            {}
variable "api_gateway_id"              {}
variable "root_resource_id"            {}
variable "api_gateway_arn"             {}
variable "default_lambda_role_arn"     {}
variable "lambda_layer_arn"            {}