variable "domain_zone_id"           {}
variable "dev_bucket_id"            {}
variable "aws_profile"              {}
variable "default_lambda_role_arn"  {}
variable "service_domain"           {}
variable "wildcard_certificate_arn" {}
variable "lambda_layer_arn"         {}
variable "create_schema_utility"    {}
variable "db_name"                  {}