variable "aws_access_key"              {}
variable "aws_secret_key"              {}
variable "aws_region"                  {}
variable "aws_profile"                 {}
variable "storage_bucket_id"           {}
variable "dev_bucket_id"               {}
variable "public_subnet_id"            {}
variable "worker_ami"                  {}
variable "api_gateway_id"              {}
variable "root_resource_id"            {}
variable "api_gateway_arn"             {}
variable "default_lambda_role_arn"     {}
variable "allow_ssh_security_group_id" {}